apiVersion: v1
kind: Secret
metadata:
  name: webapp-secret
  namespace: fullstack-app
type: Opaque
data:
  MONGODB_URI: bW9uZ29kYjovL21vbmdvLXNlcnZpY2U6MjcwMTcvdGVzdA== # mongodb://mongo-service:27017/test
